require 'ckeditor'
require 'coffee_script'
require 'sass/rails'
require 'solidus_core'
require 'solidus_editor/version'
require 'spree_editor/config'
require 'solidus_editor/engine'
require 'tinymce-rails'
